### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by abusedly** [BurakYs/bot-template#6]
Hello. I get this error when running... How would I go about fixing this?

```
TypeError [ClientMissingIntents]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\atrea\node_modules\discord.js\src\client\Client.js:509:13)
    at new Client (C:\Users\atrea\node_modules\discord.js\src\client\Client.js:78:10)
    at Object.<anonymous> (C:\Users\atrea\OneDrive\Desktop\bot-template-main\loaders\listeners.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at module.exports.loader (C:\Users\atrea\OneDrive\Desktop\bot-template-main\loaders\base.js:143:19) {
  code: 'ClientMissingIntents'
}
```

Thanks in advance.

**Comment by BurakYs** [comment]
This error occurs when you don't add the intents you use to the [Client](https://github.com/BurakYs/bot-template/blob/main/loaders/base.js#L15). 
Please check [Discord.JS Guide](https://discordjs.guide/popular-topics/intents.html#enabling-intents)
